apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-ga-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app-ga
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s

