apiVersion: v1
kind: Service
metadata:
  name: app-ga
  namespace: default
  labels:
    app: app-ga
spec:
  selector:
    app: app-ga
  ports:
    - name: http
      port: 8080       
      targetPort: 8080  
    - name: metrics
      port: 8000        
      targetPort: 8080   

